---
inherit_gem:
  dox-style:
    - ".rubocop.yml"

Env/UseFetch:
  Exclude:
    - "./bin/*"

Metrics/BlockLength:
  Exclude:
    - "./**/*_spec*.rb"
    - "./*.gemspec"
    - "./spec/*_helper*.rb"
    - "Gemfile"

Metrics/ModuleLength:
  Exclude:
    - "./**/*_spec*.rb"

Metrics/MethodLength:
  Exclude:
    - "./**/*_spec*.rb"
