language: ruby
before_install:
  - gem update bundler
rvm:
  - 2.1.1
  - 2.1.2
  - 2.1.3
  - 2.1.4
  - 2.2.2
  - 2.2.3
  - 2.3.1
services:
  - elasticsearch
before_script:
  - sleep 5
env:
  global:
    - secure: "HZa3D2GGwC6Jl062LJulbWZLTCieeBFC3FOJrArC5ul7ACGR5CEtANe0/UTnIf/Ad40p7I5VhiTdNFTcHunTbNc7Ae7dE5fOkiBHtxo/zwgpvHZK0iPvIoxsSfdcHobHeaF7NvfcXUkYUKcdRUyplHdB56eHQqYPVsah66K/4XA="
