version: 2.1

workflows:
  version: 2.1
  main:
    jobs:
      - build
jobs:
  build:
    executor: ruby-2.2.3
    docker:
      - image: ruby-2.2.3
      - image: elastic/elasticsearch:6.8.2
        environment:
          - xpack.security.enabled=false
    steps:
      - checkout
      - run:
        name: Run Tests
        command: bundle exec rspec 
