version: 2.1

orbs:
  gem: doximity/gem-publisher@0

executors:
  ruby_2_6:
    resource_class: small
    docker:
      - image: circleci/ruby:2.6
      - image: elastic/elasticsearch:6.8.2
        environment:
          - xpack.security.enabled=false

# yaml anchor filters
master_only: &master_only
  filters:
    branches:
      only: master
    tags:
      ignore: /.*/
pr_only: &pr_only
  filters:
    branches:
      ignore: master
    tags:
      ignore: /.*/
version_tags_only: &version_tags_only
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^v.*/

jobs:
  build_2_6:
    executor: ruby_2_6
    steps:
      - checkout
      - restore_cache:
          keys:
            - gem-cache-2_6-v2-{{ checksum "Gemfile.lock" }}
            - gem-cache-2_6-v2-
      - run:
          name: Install Ruby Dependencies
          command: bundle check --path=vendor/bundle || bundle install --local --frozen --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: gem-cache-2_6-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
      - run:
          name: Run Tests
          command: bundle exec rspec
      - run:
          name: Build documentation
          command: bundle exec rake ci:doc
      - store_artifacts:
          name: Saves documentation
          path: doc
      - persist_to_workspace:
          root: .
          paths:
            - vendor/bundle
workflows:
  version: 2
  trunk:
    jobs:
      - build_2_6:
          <<: *master_only
      - gem/build:
          <<: *master_only
          name: gem-build
          requires:
            - build_2_6

  pull-requests:
    jobs:
      - build_2_6:
          <<: *pr_only
      - gem/build:
          <<: *pr_only
          name: gem-build
          requires:
            - build_2_6
      - pre-release-approval:
          <<: *pr_only
          type: approval
          requires:
            - gem-build
      - gem/publish:
          <<: *pr_only
          name: gem-publish
          to_nexus: true
          pre_release: true
          requires:
            - pre-release-approval
          context: artifact_publishing

  final-release:
    jobs:
      - build_2_6:
          <<: *version_tags_only
      - gem/build:
          <<: *version_tags_only
          name: gem-build
          requires:
            - build_2_6
      - gem/publish:
          <<: *version_tags_only
          name: gem-publish
          to_nexus: true
          pre_release: false
          requires:
            - gem-build
          context: artifact_publishing
