version: 2

workflows:
  version: 2
  main:
    jobs:
      - build
jobs:
  build:
    resource_class: small
    docker:
      - image: ruby:2.5
      - image: elastic/elasticsearch:6.8.2
        environment:
          - xpack.security.enabled=false
    steps:
      - restore_cache:
          keys:
            - gem-cache-v2-{{ checksum "Gemfile.lock" }}
            - gem-cache-v2-
      - checkout
      - run:
          name: Install Ruby Dependencies
          command: bundle install
      - run:
          name: Run Tests
          command: bundle exec rspec
      - save_cache:
          key: gem-cache-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
            - ./vendor/cache
